version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: daily-activity-app
    container_name: daily-activity-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - activity-network

  webserver:
    image: nginx:alpine
    container_name: daily-activity-webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - activity-network
  db:
    image: mysql:5.7
    container_name: daily-activity-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - activity-network
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: daily-activity-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: daily-activity-db
      PMA_PORT: 3306
      PMA_USER: dailyuser
      PMA_PASSWORD: password
    networks:
      - activity-network

networks:
  activity-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
